import React from 'react';
import Router from 'next/router';
import Head from 'next/head';

import { Inter } from '@next/font/google';
import { signInwithGoogle } from '../Firebase';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const handleSigninClick = async () => {
    await signInwithGoogle();
    const userAuthenticated = sessionStorage.getItem('userAuthenticated');
    if (userAuthenticated) {
      Router.push('/home');
    }
  };

  return (
    <>
      <Head>
        <title>StockApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full min-h-[100vh]">
        <div className="w-full h-full min-h-[100vh] flex flex-wrap items-center justify-center">
          <div className='mr-4'>
            <div className='text-lg font-bold text-[#006ce6]'>
              Stock App
            </div>
            <div className='mr-4'>
              By Sreejel C Anil
            </div>
          </div>
          <button type="button" onClick={handleSigninClick} className="bg-[#006ce6] hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-full sm:ml-4 sm:mt-2">
            Sign In With Google
          </button>
        </div>
      </main>
    </>
  );
}
